<?php
declare(strict_types=1);

return [
    'code_to_callmanager' => [
        // detailed_hangup_cause_code => callmanager_hangup_cause
        '0' => 'provider.temp.failure',
        '1' => 'number.failure',
        '2' => 'number.failure',
        '3' => 'number.failure',
        '4' => 'number.failure',
        '5' => 'number.failure',
        '6' => 'provider.failure',
        '7' => 'normal.clearing',
        '8' => 'normal.clearing',
        '9' => 'normal.clearing',
        '16' => 'normal.clearing',
        '17' => 'busy',
        '18' => 'busy',
        '19' => 'busy',
        '20' => 'number.temp.failure',
        '21' => 'number.temp.failure',
        '22' => 'number.failure',
        '26' => 'provider.temp.failure',
        '27' => 'provider.failure',
        '28' => 'number.failure',
        '29' => 'number.temp.failure',
        '30' => 'normal.clearing',
        '31' => 'normal.clearing',
        '34' => 'provider.temp.failure',
        '38' => 'provider.temp.failure',
        '39' => 'provider.temp.failure',
        '40' => 'provider.temp.failure',
        '41' => 'provider.temp.failure',
        '42' => 'provider.temp.failure',
        '43' => 'provider.failure',
        '44' => 'provider.temp.failure',
        '45' => 'provider.temp.failure',
        '46' => 'number.temp.failure',
        '47' => 'provider.temp.failure',
        '49' => 'provider.failure',
        '50' => 'provider.failure',
        '52' => 'provider.failure',
        '53' => 'provider.failure',
        '54' => 'provider.failure',
        '55' => 'number.failure',
        '57' => 'provider.failure',
        '58' => 'provider.failure',
        '62' => 'provider.temp.failure',
        '63' => 'provider.failure',
        '65' => 'provider.failure',
        '66' => 'provider.failure',
        '69' => 'provider.failure',
        '70' => 'provider.failure',
        '79' => 'provider.failure',
        '81' => 'number.temp.failure',
        '82' => 'provider.failure',
        '83' => 'provider.temp.failure',
        '84' => 'provider.temp.failure',
        '85' => 'provider.temp.failure',
        '86' => 'provider.temp.failure',
        '87' => 'number.failure',
        '88' => 'provider.failure',
        '90' => 'number.failure',
        '91' => 'provider.temp.failure',
        '95' => 'provider.temp.failure',
        '96' => 'provider.temp.failure',
        '97' => 'provider.failure',
        '98' => 'provider.temp.failure',
        '99' => 'provider.failure',
        '100' => 'normal.clearing',
        '101' => 'provider.temp.failure',
        '102' => 'provider.temp.failure',
        '103' => 'provider.failure',
        '110' => 'provider.temp.failure',
        '111' => 'provider.failure',
        '127' => 'provider.temp.failure',
        '180' => 'normal.clearing',
        '181' => 'normal.clearing',
        '182' => 'normal.clearing',
        '183' => 'normal.clearing',
        '200' => 'normal.clearing',
        '300' => 'number.failure',
        '301' => 'number.failure',
        '302' => 'number.failure',
        '305' => 'number.failure',
        '380' => 'number.failure',
        '400' => 'provider.failure',
        '401' => 'provider.failure',
        '402' => 'provider.failure',
        '403' => 'provider.failure',
        '404' => 'number.failure',
        '405' => 'provider.failure',
        '406' => 'provider.failure',
        '407' => 'provider.failure',
        '408' => 'provider.temp.failure',
        '410' => 'provider.failure',
        '413' => 'number.temp.failure',
        '414' => 'number.temp.failure',
        '415' => 'provider.failure',
        '416' => 'provider.failure',
        '420' => 'number.failure',
        '421' => 'normal.clearing',
        '422' => 'provider.failure',
        '423' => 'normal.clearing',
        '480' => 'provider.temp.failure',
        '481' => 'provider.temp.failure',
        '482' => 'provider.temp.failure',
        '483' => 'provider.temp.failure',
        '484' => 'normal.clearing',
        '485' => 'provider.temp.failure',
        '486' => 'busy',
        '487' => 'provider.temp.failure',
        '488' => 'provider.failure',
        '491' => 'provider.temp.failure',
        '493' => 'provider.failure',
        '500' => 'provider.temp.failure',
        '501' => 'provider.failure',
        '502' => 'provider.temp.failure',
        '503' => 'provider.temp.failure',
        '504' => 'normal.clearing',
        '505' => 'provider.failure',
        '513' => 'provider.temp.failure',
        '600' => 'busy',
        '603' => 'number.temp.failure',
        '604' => 'number.failure',
        '606' => 'provider.failure',
        '759' => 'provider.temp.failure',
        '760' => 'sit.intercept',
        '761' => 'sit.vacant',
        '762' => 'sit.nocircuit',
        '763' => 'sit.reorder',
    ],
    'callmanager_to_system' => [
        'normal.clearing' => 'CALL_HANGUP',
        'busy' => 'BUSY',
        'number.temp.failure' => 'NUMBER_TEMP_FAILURE',
        'sit.vacant' => 'NUMBER_FAILURE',
        'number.failure' => 'NUMBER_FAILURE',
        'sit.reorder' => 'ATTEMPT_FAILED',
        'sit.nocircuit' => 'ATTEMPT_FAILED',
        'sit.intercept' => 'ATTEMPT_FAILED',
        'provider.temp.failure' => 'PROVIDER_TEMP_FAILURE',
        'provider.failure' => 'PROVIDER_FAILURE',
    ],
    'allowed_system_dispositions' => [
        'CONNECTED',
        'CALL_DROP',
        'CALL_HANGUP',
        'NO_ANSWER',
        'PROVIDER_FAILURE',
        'BUSY',
        'PROVIDER_TEMP_FAILURE',
        'NUMBER_FAILURE',
        'CALL_NOT_PICKED',
        'ATTEMPT_FAILED',
        'NUMBER_TEMP_FAILURE',
    ],
];
